#spring:
#  application:
#    name: back-demo
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://49.232.160.134:3306/klww_mdm?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=CTT
#    username: root
#    password: root-test
#    type: com.alibaba.druid.pool.DruidDataSource

spring:
  application:
    name: back-demo
  datasource:
#    driverClassName: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:mysql://db-01.test.otransferx.com:3306/bpm_risk?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#    username: otransfer
#    password: otransfer
#    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://49.232.160.134:3306/bpm_risk?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=CTT
    username: root
    password: root-test
    type: com.alibaba.druid.pool.DruidDataSource