customer:
  ip: ENC(zVF/QuMVFu7MmRh/LGH5b5yujKJvcJ8e58tzVArjemxWSiPX8JkLjU8sTaqWPHwE)
  redis:
    port: ENC(6bEtY0PUFqbHPrAkgkiXL54l3X2SUh9BHf52SLjt+06CUBo25kZA7T9TUa6vcBQZ)
  mysql:
    port: ENC(E5Z2WPIUfIFIL7rqFAKUKG3lPv3IkgLKdl3cmHlftRKIhbs540FXyW6v6eKM3yDi)
    user: ENC(t2InYqCRG8KNy3ytpUX8L5+9yz8jZqJccDmpdrOA+opN5in1ylmU7Pved7c0aGiQ)
    password: ENC(t2InYqCRG8KNy3ytpUX8L5+9yz8jZqJccDmpdrOA+opN5in1ylmU7Pved7c0aGiQ)
spring:
  application:
    name: back-demo
  datasource:
    dynamic:
      primary: risk #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        risk:
          url: jdbc:mysql://${customer.ip}:${customer.mysql.port}/bpm_risk?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=CTT
#          url: jdbc:mysql://${customer.ip}:${customer.mysql.port}/bpm_risk?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=CTT
          username: ${customer.mysql.user}
          password: ${customer.mysql.password}
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
        user:
          url: jdbc:mysql://${customer.ip}:${customer.mysql.port}/bpm_user?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=CTT
          username: ${customer.mysql.user}
          password: ${customer.mysql.password}
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
      p6spy: true
  redis:
    host: ${customer.ip}
    port: ${customer.redis.port}
    database: 0

  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
#spring:
#  datasource:
#    dynamic:
#      primary: risk #设置默认的数据源或者数据源组,默认值即为master
#      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
#      datasource:
#        risk:
#          url: jdbc:p6spy:mysql://xxxx:xxx/bpm_risk?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=CTT
#          username: xxxx
#          password: xxxxxx
#          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#          type: com.alibaba.druid.pool.DruidDataSource
#        user:
#          url: jdbc:p6spy:mysql://xxxx:xxxx/bpm_user?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=CTT
#          username: xxxxx
#          password: xxxxx
#          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#          type: com.alibaba.druid.pool.DruidDataSource
##        slave_2:
##          url: ENC(xxxxx) # 内置加密,使用请查看详细文档
##          username: ENC(xxxxx)
##          password: ENC(xxxxx)
##          driver-class-name: com.mysql.jdbc.Driver
##          schema: db/schema.sql # 配置则生效,自动初始化表结构
##          data: db/data.sql # 配置则生效,自动初始化数据
##          continue-on-error: true # 默认true,初始化失败是否继续
##          separator: ";" # sql默认分号分隔符