#spring:
#  application:
#    name: back-demo
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://49.232.160.134:3306/klww_mdm?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=CTT
#    username: root
#    password: root-test
#    type: com.alibaba.druid.pool.DruidDataSource

spring:
  application:
    name: back-demo
  datasource:
#    driverClassName: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:mysql://db-01.test.otransferx.com:3306/bpm_risk?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#    username: otransfer
#    password: otransfer
#    type: com.alibaba.druid.pool.DruidDataSource

#    driverClassName: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:mysql://49.232.160.134:3306/bpm_risk?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=CTT
#    username: root
#    password: root-test
#    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: risk #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        risk:
          url: jdbc:mysql://49.232.160.134:3306/bpm_risk?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=CTT
          username: root
          password: root-test
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
        user:
          url: jdbc:mysql://49.232.160.134:3306/bpm_user?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=CTT
          username: root
          password: root-test
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
      p6spy: true
  redis:
    host: 49.232.160.134
    port: 6379
    database: 0

  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
#spring:
#  datasource:
#    dynamic:
#      primary: risk #设置默认的数据源或者数据源组,默认值即为master
#      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
#      datasource:
#        risk:
#          url: jdbc:p6spy:mysql://49.232.160.134:3306/bpm_risk?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=CTT
#          username: root
#          password: root-test
#          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#          type: com.alibaba.druid.pool.DruidDataSource
#        user:
#          url: jdbc:p6spy:mysql://49.232.160.134:3306/bpm_user?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=CTT
#          username: root
#          password: root-test
#          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#          type: com.alibaba.druid.pool.DruidDataSource
##        slave_2:
##          url: ENC(xxxxx) # 内置加密,使用请查看详细文档
##          username: ENC(xxxxx)
##          password: ENC(xxxxx)
##          driver-class-name: com.mysql.jdbc.Driver
##          schema: db/schema.sql # 配置则生效,自动初始化表结构
##          data: db/data.sql # 配置则生效,自动初始化数据
##          continue-on-error: true # 默认true,初始化失败是否继续
##          separator: ";" # sql默认分号分隔符